version: "3.8"

services:
  client:
    image: ad956/fitness-networking-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_SERVER_URL=${VITE_SERVER_URL}
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}

  server:
    image: ad956/fitness-networking-backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_URL=${DB_URL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - GUSER=${GUSER}
      - GPASS=${GPASS}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - FITNESS_NETWORKING_EMAIL=${FITNESS_NETWORKING_EMAIL}
