services:
  - type: web
    runtime: docker
    name: fitness-networking-frontend
    image:
      url: docker.io/fitness-networking-frontend:latest
    region: oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    runtime: docker
    name: fitness-networking-backend
    image: 
     url: docker.io/fitness-networking-backend:latest
    region: oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

databases:
  - name: fitness-networking-db
    databaseName: fitness
    plan: free
