services:
  - type: web
    name: fitness-networking-frontend
    runtime: docker
    image:
      url: docker.io/fitness-networking-frontend:latest
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: fitness-networking-backend
    runtime: docker
    image:
      url: docker.io/fitness-networking-backend:latest
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"

databases:
  - name: fitness-networking-db
    databaseName: fitness

version: "1"