services:
  - type: web
    name: fitness-networking
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    autoDeploy: true
    rootDir: ./client
    # healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: fitness-networking-backend
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    autoDeploy: true
    # healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DB_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: GUSER
        sync: false
      - key: GPASS
        sync: false
      - key: BCRYPT_ROUNDS
        sync: false
      - key: FITNESS_NETWORKING_EMAIL
        sync: false

databases:
  - name: fitness-networking-db
    databaseName: fitness
    plan: free