name: Docker Build and Push Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6.3.0
        with:
          context: ./client
          push: true
          tags: ad956/fitness-networking-frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v6.3.0
        with:
          context: ./server
          push: true
          tags: ad956/fitness-networking-backend:latest
